### PR TITLE
Fix/uglifier

### PR DESCRIPTION
**Pull request by pavanvo**

### CODE REVIEW

**Comment by arBmind** [comment]
Why do we need that? - So far I have not seen any issues. But maybe I am using it wrongly ;)

**Comment by pavanvo** [comment]
> Why do we need that? - So far I have not seen any issues. But maybe I am using it wrongly ;)

I get this error when trying to compile, without that fix
redmine-5.0.4$ bundle exec rake redmine:plugins:assets RAILS_ENV=production
rake aborted!
Uglifier::Error: Unexpected token: punc ()). To use ES6 syntax, harmony mode must be enabled with Uglifier.new(:harmony => true).

  1 /**
  2  * File generated by js-routes 2.2.4
  3  * Based on Rails 6.1.7 routes of RedmineApp::Application
  4  */
 => (typeof window !== 'undefined' ? window : this).hourglassRoutes = (() => {
  6     const hasProp = (value, key) => Object.prototype.hasOwnProperty.call(value, key);
  7     let NodeTypes;
  8     (function (NodeTypes) {
  9         NodeTypes[NodeTypes["GROUP"] = 1] = "GROUP";
 10         NodeTypes[NodeTypes["CAT"] = 2] = "CAT";
 11         NodeTypes[NodeTypes["SYMBOL"] = 3] = "SYMBOL";
 12         NodeTypes[NodeTypes["OR"] = 4] = "OR";
 13         NodeTypes[NodeTypes["STAR"] = 5] = "STAR";

**Comment by pavanvo** [comment]
Btw I use this ugly hack to compile
https://github.com/pavanvo/redmine_hourglass/commit/672bc52c6ecd44f534b2785f75bedc8d594179cb

**Comment by arBmind** [comment]
> Btw I use this ugly hack to compile [pavanvo@672bc52](https://github.com/pavanvo/redmine_hourglass/commit/672bc52c6ecd44f534b2785f75bedc8d594179cb)

I found a better work around ;)

**Pull request merged**
